-- ==========================================================
-- BookMyShow MySQL Database Schema & Dummy Data Script
-- Run this script in your MySQL Workbench to create
-- the tables and populate dummy data.
-- ==========================================================

-- 1. Create Tables
CREATE TABLE REGION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    NAME VARCHAR(255)
);

CREATE TABLE THEATER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    NAME VARCHAR(255),
    REGION_ID BIGINT,
    FOREIGN KEY (REGION_ID) REFERENCES REGION(ID)
);

CREATE TABLE SCREEN (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    NAME VARCHAR(255),
    THEATER_ID BIGINT,
    FOREIGN KEY (THEATER_ID) REFERENCES THEATER(ID)
);

CREATE TABLE SCREEN_FEATURES (
    SCREEN_ID BIGINT,
    FEATURES INT,
    FOREIGN KEY (SCREEN_ID) REFERENCES SCREEN(ID)
);

CREATE TABLE MOVIE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DESCRIPTION VARCHAR(255),
    DURATION_IN_MINS INT,
    NAME VARCHAR(255),
    RATING FLOAT
);

CREATE TABLE MOVIE_LANGUAGES (
    MOVIE_ID BIGINT,
    LANGUAGES VARCHAR(255),
    FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE(ID)
);

CREATE TABLE MOVIE_FEATURES (
    MOVIE_ID BIGINT,
    FEATURES ENUM('TWO_D','THREE_D','IMAX','DOLBY'),
    FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE(ID)
);

CREATE TABLE SEAT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    COL_VAL INT,
    ROW_VAL INT,
    SEAT_NUMBER VARCHAR(255),
    SEAT_TYPE ENUM('VIP','PREMIUM','GOLD','SILVER'),
    SCREEN_ID BIGINT,
    FOREIGN KEY (SCREEN_ID) REFERENCES SCREEN(ID)
);

CREATE TABLE APP_USER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    EMAIL VARCHAR(255),
    NAME VARCHAR(255),
    PASSWORD VARCHAR(255)
);

CREATE TABLE _SHOW (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    END_TIME DATETIME,
    START_TIME DATETIME,
    MOVIE_ID BIGINT,
    SCREEN_ID BIGINT,
    FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE(ID),
    FOREIGN KEY (SCREEN_ID) REFERENCES SCREEN(ID)
);

CREATE TABLE SHOW_SEAT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRICE DOUBLE,
    STATUS ENUM('AVAILABLE','UNAVAILABLE','BLOCKED','BOOKED'),
    SEAT_ID BIGINT,
    SHOW_ID BIGINT,
    FOREIGN KEY (SEAT_ID) REFERENCES SEAT(ID),
    FOREIGN KEY (SHOW_ID) REFERENCES _SHOW(ID)
);

CREATE TABLE BOOKING (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    AMOUNT DOUBLE,
    BOOKING_STATUS ENUM('CONFIRMED','IN_PROGRESS','CANCELLED'),
    SHOW_ID BIGINT,
    USER_ID BIGINT,
    FOREIGN KEY (SHOW_ID) REFERENCES _SHOW(ID),
    FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID)
);

CREATE TABLE BOOKING_SHOW_SEATS (
    BOOKING_ID BIGINT,
    SHOW_SEATS_ID BIGINT,
    FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING(ID),
    FOREIGN KEY (SHOW_SEATS_ID) REFERENCES SHOW_SEAT(ID)
);

CREATE TABLE PAYMENT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    AMOUNT DOUBLE,
    PAYMENT_PROVIDER ENUM('RAZORPAY','STRIPE','PAYU'),
    PAYMENT_STATUS ENUM('SUCCESS','FAILURE','PENDING'),
    REFERENCE_NUMBER VARCHAR(255),
    BOOKING_ID BIGINT,
    FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING(ID)
);

-- ==========================================================
-- 2. Insert Dummy Data
-- ==========================================================

-- Insert User
INSERT INTO APP_USER (EMAIL, NAME, PASSWORD) VALUES ('dummy@example.com', 'Dummy User', 'password123');

-- Insert Region
INSERT INTO REGION (NAME) VALUES ('Mumbai');

-- Insert Theater
INSERT INTO THEATER (NAME, REGION_ID) VALUES ('PVR ICON Andheri', 1);

-- Insert Screen
INSERT INTO SCREEN (NAME, THEATER_ID) VALUES ('Screen 1', 1);
INSERT INTO SCREEN_FEATURES (SCREEN_ID, FEATURES) VALUES (1, 0); -- TWO_D
INSERT INTO SCREEN_FEATURES (SCREEN_ID, FEATURES) VALUES (1, 3); -- DOLBY

-- Insert Movie
INSERT INTO MOVIE (NAME, DESCRIPTION, DURATION_IN_MINS, RATING) VALUES ('Inception', 'A mind-bending thriller', 148, 8.8);
INSERT INTO MOVIE_LANGUAGES (MOVIE_ID, LANGUAGES) VALUES (1, 'English');
INSERT INTO MOVIE_LANGUAGES (MOVIE_ID, LANGUAGES) VALUES (1, 'Hindi');
INSERT INTO MOVIE_FEATURES (MOVIE_ID, FEATURES) VALUES (1, 'TWO_D');
INSERT INTO MOVIE_FEATURES (MOVIE_ID, FEATURES) VALUES (1, 'IMAX');

-- Insert Seats for Screen 1
INSERT INTO SEAT (SEAT_NUMBER, ROW_VAL, COL_VAL, SEAT_TYPE, SCREEN_ID) VALUES 
('A1', 1, 1, 'VIP', 1), ('A2', 1, 2, 'VIP', 1), ('A3', 1, 3, 'VIP', 1), ('A4', 1, 4, 'VIP', 1), ('A5', 1, 5, 'VIP', 1),
('A6', 1, 6, 'VIP', 1), ('A7', 1, 7, 'VIP', 1), ('A8', 1, 8, 'VIP', 1), ('A9', 1, 9, 'VIP', 1), ('A10', 1, 10, 'VIP', 1);

-- Insert Show (Tomorrow)
INSERT INTO _SHOW (MOVIE_ID, SCREEN_ID, START_TIME, END_TIME) 
VALUES (1, 1, DATE_ADD(NOW(), INTERVAL 1 DAY), DATE_ADD(DATE_ADD(NOW(), INTERVAL 1 DAY), INTERVAL 148 MINUTE));

-- Insert ShowSeats
INSERT INTO SHOW_SEAT (SHOW_ID, SEAT_ID, PRICE, STATUS) VALUES 
(1, 1, 500.0, 'AVAILABLE'), (1, 2, 500.0, 'AVAILABLE'), (1, 3, 500.0, 'AVAILABLE'), (1, 4, 500.0, 'AVAILABLE'), (1, 5, 500.0, 'AVAILABLE'),
(1, 6, 500.0, 'AVAILABLE'), (1, 7, 500.0, 'AVAILABLE'), (1, 8, 500.0, 'AVAILABLE'), (1, 9, 500.0, 'AVAILABLE'), (1, 10, 500.0, 'AVAILABLE');

COMMIT;
